### ISSUE TITLE
Missing Eigen/Core!

### ISSUE THREAD

**Issue by jrkhan** [gradientspace/UnrealMeshProcessingTools#1]
Looks like the Eigen's .gitignore excludes `core`
https://gitlab.com/libeigen/eigen/-/blob/master/.gitignore#L11
So, probably due to case sensitivity differences, these files/directories didn't get added to the version of Eigen included here (which in turn resulted in a few plugin build failures until moving them over locally)
https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/Core
https://gitlab.com/libeigen/eigen/-/tree/master/Eigen/src/Core

Smoothing mesehs in editor seems to be working well once those files were added!

Wondering if you'd be open to a PR to add the files?
(Or, unrelated, perhaps open to PR's in general for exposing additional libigl functions as editor tools?)

**Comment by rms80** [comment]
this has been fixed
